#!/usr/bin/env python3
"""Turn the client-data sheets into SQL that loads them, idempotently.

    python3 db/import-client-data.py --from ~/vts/docs/internal/client-data \
      | psql -q -v ON_ERROR_STOP=1 -d reckon_dev

Emits SQL rather than connecting, for the same reason db/apply.sh pipes over
stdin: nothing here needs a database driver installed, and the SQL can be read
before it is run.

Re-running changes nothing. Every sheet is keyed by a name, matched on that
name, and updated in place -- so correcting a spelling in a sheet renames the
row rather than creating a second one only if the key itself is unchanged. A
changed key is a new row, which is why check.py exists.

A district rate is imported only with an effective date. "rates in a csv with a
proper effective date (not arbitrary validated at timestamp)" -- 18 Aug 2026:
the day a rate was looked up is not the day it took effect, and an invoice
dated before the real one would resolve the wrong rate.
"""

import argparse
import csv
import pathlib
import sys


def lit(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def num(v):
    return "NULL" if v in (None, "") else str(v)


def rows(d, name):
    with (d / name).open(newline="") as f:
        return [{k: (v.strip() if isinstance(v, str) else v) for k, v in r.items()}
                for r in csv.DictReader(f)]


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--from", dest="src", required=True, help="the client-data directory")
    args = ap.parse_args()

    d = pathlib.Path(args.src).expanduser()
    clients = rows(d, "clients.csv")
    districts = rows(d, "tax-districts.csv")
    locations = rows(d, "locations.csv")
    sites = rows(d, "sites.csv")

    skipped = [r["tax_district"] for r in districts if not r.get("effective_from")]
    rated = [r for r in districts if r.get("effective_from")]

    # Contacts are named in two places and are one list.
    contacts = {}
    for r in clients:
        if r["primary_contact"]:
            contacts[r["primary_contact"]] = (r.get("email"), r.get("phone"))
    for r in sites:
        if r["site_contact"]:
            contacts.setdefault(r["site_contact"], (None, None))

    o = sys.stdout.write
    o("-- Generated by db/import-client-data.py. Do not edit; edit the sheets.\n")
    o(f"-- {len(clients)} clients, {len(sites)} sites, {len(locations)} addresses, "
      f"{len(districts)} districts, {len(contacts)} contacts.\n")
    if skipped:
        o(f"-- No effective date, so no rate imported: {', '.join(skipped)}\n")
    o("\nBEGIN;\n")

    def temp(name, cols, values):
        o(f"\nCREATE TEMP TABLE {name} ({cols}) ON COMMIT DROP;\n")
        if values:
            o(f"INSERT INTO {name} VALUES\n  " + ",\n  ".join(values) + ";\n")

    temp("imp_contact", "name text, email text, phone text",
         [f"({lit(n)}, {lit(e)}, {lit(p)})" for n, (e, p) in sorted(contacts.items())])
    temp("imp_client", "name text, contact text, note text",
         [f"({lit(r['client'])}, {lit(r['primary_contact'])}, {lit(r['notes'])})"
          for r in clients])
    temp("imp_district", "name text, county text, rate_pct numeric, "
                         "effective_from date, verified_on date, source text",
         [f"({lit(r['tax_district'])}, {lit(r['county'])}, {num(r['rate_pct'])}, "
          f"{lit(r['effective_from'])}, {lit(r['verified_on'])}, "
          f"{lit(r.get('source'))})" for r in districts])
    temp("imp_location", "label text, street text, city text, postcode text, "
                         "district text, miles numeric, minutes int, verified_on date",
         [f"({lit(r['location'])}, {lit(r['street'])}, {lit(r['city'])}, {lit(r['zip'])}, "
          f"{lit(r['tax_district'])}, {num(r['round_trip_miles'])}, "
          f"{num(r['drive_minutes'])}, {lit(r.get('verified_on'))})" for r in locations])
    temp("imp_site", "client text, location text, label text, contact text",
         [f"({lit(r['client'])}, {lit(r['location'])}, {lit(r['label'])}, "
          f"{lit(r['site_contact'])})" for r in sites])

    o("""
-- A name naming nothing is a typo in a sheet, not a row to invent.
DO $$
DECLARE bad text;
BEGIN
  SELECT string_agg(DISTINCT district, ', ') INTO bad
    FROM imp_location WHERE district IS NOT NULL
     AND district NOT IN (SELECT name FROM imp_district);
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'locations name unknown districts: %', bad; END IF;

  SELECT string_agg(DISTINCT client, ', ') INTO bad
    FROM imp_site WHERE client NOT IN (SELECT name FROM imp_client);
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'sites name unknown clients: %', bad; END IF;

  SELECT string_agg(DISTINCT location, ', ') INTO bad
    FROM imp_site WHERE location NOT IN (SELECT label FROM imp_location);
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'sites name unknown locations: %', bad; END IF;
END $$;

-- contacts -------------------------------------------------------------------
INSERT INTO contact (name, email, phone)
SELECT i.name, i.email, i.phone FROM imp_contact i
 WHERE NOT EXISTS (SELECT 1 FROM contact c WHERE c.name = i.name);

UPDATE contact c SET email = coalesce(i.email, c.email),
                     phone = coalesce(i.phone, c.phone)
  FROM imp_contact i WHERE c.name = i.name
   AND (c.email, c.phone) IS DISTINCT FROM
       (coalesce(i.email, c.email), coalesce(i.phone, c.phone));

-- districts and their rates ---------------------------------------------------
INSERT INTO tax_district (name, county)
SELECT name, county FROM imp_district
    ON CONFLICT (name) DO UPDATE SET county = EXCLUDED.county;

INSERT INTO tax_district_rate (district_id, rate_pct, effective_from, verified_on, source)
SELECT d.id, i.rate_pct, i.effective_from, i.verified_on,
       coalesce(i.source, 'client-data sheets')
  FROM imp_district i JOIN tax_district d ON d.name = i.name
 WHERE i.effective_from IS NOT NULL
    ON CONFLICT (district_id, effective_from)
    DO UPDATE SET rate_pct = EXCLUDED.rate_pct,
                  verified_on = EXCLUDED.verified_on,
                  source = EXCLUDED.source;

-- addresses -------------------------------------------------------------------
INSERT INTO location (label, street, city, region, postcode,
                      round_trip_miles, drive_minutes, tax_district_id,
                      district_verified_on)
SELECT i.label, i.street, i.city, 'CA', i.postcode, i.miles, i.minutes, d.id,
       i.verified_on
  FROM imp_location i LEFT JOIN tax_district d ON d.name = i.district
 WHERE NOT EXISTS (SELECT 1 FROM location l WHERE l.label = i.label);

UPDATE location l
   SET street = i.street, city = i.city, postcode = i.postcode,
       round_trip_miles = i.miles, drive_minutes = i.minutes,
       tax_district_id = d.id, district_verified_on = i.verified_on
  FROM imp_location i LEFT JOIN tax_district d ON d.name = i.district
 WHERE l.label = i.label;

-- clients ---------------------------------------------------------------------
INSERT INTO entity (name)
SELECT i.name FROM imp_client i
 WHERE NOT EXISTS (SELECT 1 FROM entity e WHERE e.name = i.name);

INSERT INTO entity_contact (entity_id, contact_id, is_primary)
SELECT e.id, c.id, true
  FROM imp_client i JOIN entity e ON e.name = i.name
                    JOIN contact c ON c.name = i.contact
 WHERE i.contact IS NOT NULL
    ON CONFLICT (entity_id, contact_id) DO UPDATE SET is_primary = true;

-- sites: the client at the address, named and staffed as that client sees it ---
INSERT INTO entity_location (entity_id, location_id, label, contact_id)
SELECT e.id, l.id, i.label, c.id
  FROM imp_site i
  JOIN entity   e ON e.name  = i.client
  JOIN location l ON l.label = i.location
  LEFT JOIN contact c ON c.name = i.contact
    ON CONFLICT (entity_id, location_id)
    DO UPDATE SET label = EXCLUDED.label, contact_id = EXCLUDED.contact_id;

DELETE FROM entity_location el
 USING entity e
 WHERE el.entity_id = e.id
   AND e.name IN (SELECT name FROM imp_client)
   AND NOT EXISTS (
     SELECT 1 FROM imp_site i JOIN location l ON l.label = i.location
      WHERE i.client = e.name AND l.id = el.location_id);

DO $$
DECLARE orphan text;
BEGIN
  SELECT string_agg(l.label, ', ' ORDER BY l.label) INTO orphan
    FROM location l
   WHERE NOT EXISTS (SELECT 1 FROM entity_location el WHERE el.location_id = l.id);
  IF orphan IS NOT NULL THEN
    RAISE NOTICE 'no client uses: %', orphan;
  END IF;
END $$;

DO $$
DECLARE c int; s int; l int; d int; r int;
BEGIN
  SELECT count(*) INTO c FROM entity;
  SELECT count(*) INTO s FROM entity_location;
  SELECT count(*) INTO l FROM location;
  SELECT count(*) INTO d FROM tax_district;
  SELECT count(*) INTO r FROM tax_district_rate;
  RAISE NOTICE 'clients %, sites %, addresses %, districts %, rates %', c, s, l, d, r;
END $$;

COMMIT;
""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
